name: easacc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  wifi_iot: ^0.3.19
  flutter_blue_plus: ^1.33.7
  permission_handler: ^11.3.1
  webview_flutter: ^4.8.0
  flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
